---
- name: Install EPEL (RedHat/CentOS)
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure nginx user exists
  user:
    name: nginx
    system: yes
    shell: /usr/sbin/nologin
    create_home: no
  when: ansible_distribution == "Astra Linux"

- name: Install Nginx (Ubuntu/Debian)
  apt:
    name: "{{ nginx_package }}"
    state: latest
    update_cache: yes
  when: ansible_distribution == "Astra Linux"

#- name: Install Nginx (Ubuntu/Debian)
#  apt:
#    name: "{{ nginx_package }}"
#    state: latest
#    update_cache: yes
##  ignore_errors: true
#  when: ansible_distribution == "Astra Linux"
#  #ansible_os_family == "Debian" or
##        ansible_distribution == "Astra Linux" or
##        ansible_distribution == "Ubuntu"

- name: Install Nginx (RedHat/CentOS)
  yum:
    name:
      - "{{ nginx_package }}"
      - "{{ item }}"
    state: latest
  loop: "{{ nginx_modules }}"
  when: ansible_os_family == "RedHat"

- name: Create Nginx config directory
  file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Deploy Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Nginx

- name: Ensure Nginx is running
  systemd:
    name: nginx
    state: started
    enabled: yes